AllCops:
  TargetRubyVersion: 3.1.2
  Exclude:
    - "lib/middleware/exception.rb"

Style/GuardClause:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Lint/UnusedMethodArgument:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
